#--------------------------------------------------
# Install Ansible
#--------------------------------------------------
- name: Install EPEL
  become: yes
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: Install base packages
  become: yes
  yum: name={{ item }} state=latest enablerepo=epel-testing
  with_items: 
      - vim
      - nano
      - git
      - ansible


- name: Install Ansible license in home directory
  copy: src="{{ item }}" dest=/home/ec2-user/ owner=ec2-user group=ec2-user
  with_items:
    - license


- name: Create vim plugin storage directory
  file: path=/home/ec2-user/.vim/autoload state=directory owner=ec2-user group=ec2-user


- name: Install vim plugin manager
  get_url: url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim dest=/home/ec2-user/.vim/autoload/plug.vim owner=ec2-user group=ec2-user


- name: Install vimrc in home directory
  copy: src=vimrc dest=/home/ec2-user/.vimrc owner=ec2-user group=ec2-user


- name: Install nanorc in home directory
  copy: src=nanorc dest=/home/ec2-user/.nanorc owner=ec2-user group=ec2-user


- name: Copy over SSH Key to ec2-user home
  copy: src="{{ terraform_working_dir }}/{{ workshop_prefix }}-tower" dest=/home/ec2-user/.ssh/{{ workshop_prefix }}-tower mode=0400 owner=ec2-user group=ec2-user


- name: Template over ansible.cfg
  template: dest=/home/ec2-user/ansible.cfg  src=ansible.cfg.j2  owner=ec2-user group=ec2-user
